name: Weekly Progress Issue

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:

permissions:
  issues: write  # <-- This is required to create issues

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create weekly issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date();
            const weekNumber = Math.ceil(((now - new Date(now.getFullYear(), 0, 1)) / 86400000 + now.getDay() + 1) / 7);
            const issueTitle = `[Progress] Week ${weekNumber}:`;
            const issueBody = `### 📘 Weekly Progress Log\n\n- **Date Range**: \n- **✅ What I Learned**:\n- **🔧 What I Built**:\n- **🎯 What’s Next**:\n`;

            const res = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['progress', 'weekly']
            });

            console.log('Created issue: ', res.data.html_url);
