name: Weekly Progress Issue

on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 9 AM GMT+6 (which is 3 AM UTC)
  workflow_dispatch:

permissions:
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create weekly issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Function to format the date as YYYY-MM-DD
            function formatDate(date) {
              const year = date.getFullYear();
              const month = String(date.getMonth() + 1).padStart(2, '0');
              const day = String(date.getDate()).padStart(2, '0');
              return `${year}-${month}-${day}`;
            }

            // Define your custom start date
            const customStartDate = new Date('2025-05-30T00:00:00Z');
            const now = new Date();
            
            // Calculate the difference in days from the custom start date
            const diffInMilliseconds = now - customStartDate;
            const diffInDays = Math.floor(diffInMilliseconds / (1000 * 60 * 60 * 24));
            
            // Calculate the custom week number
            const customWeekNumber = Math.floor(diffInDays / 7) + 1;
            
            const issueTitle = `[Progress] Week ${customWeekNumber}:`;

            // Calculate the start and end dates of the current week relative to the custom start date
            const weeksSinceStart = Math.floor(diffInDays / 7);
            const startOfWeekOffset = weeksSinceStart * 7;
            
            const startOfWeek = new Date(customStartDate.getTime() + startOfWeekOffset * 1000 * 60 * 60 * 24);
            const endOfWeek = new Date(startOfWeek.getTime() + 6 * 1000 * 60 * 60 * 24);
            
            const startDate = formatDate(startOfWeek);
            const endDate = formatDate(endOfWeek);

            const issueBody = `### 📘 Weekly Progress Log\n\n- **Date Range**: ${startDate} to ${endDate}\n- **✅ What I Learned**:\n- **🔧 What I Built**:\n- **🎯 What’s Next**:\n`;

            const res = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['progress', 'weekly']
            });

            console.log('Created issue: ', res.data.html_url);
